IncredibleXMLParser: ITCXMLNode Class Reference
ITCXMLNode Class Reference
Navigate the XMLNode structure
Main Class representing a Incredible Transient Constant XML node.
#include <IXMLParser.h>
Public Member Functions
IXMLCStr getName () const
name of the node
IXMLCStr getText (int i=0) const
return ith text field
int nText () const
nbr of text field
ITCXMLNode getParentNode () const
return the parent node
ITCXMLNode getChildNode (int i=0) const
return ith child node
ITCXMLNode getChildNode (IXMLCStr name, int i) const
return ith child node with specific name (return an empty node if failing). If i==-1, this returns the last IXMLNode with the given name
ITCXMLNode getChildNode (IXMLCStr name, int *i=NULL) const
return next child node with specific name (return an empty node if failing)
ITCXMLNode getChildNodeWithAttribute (IXMLCStr tagName, IXMLCStr attributeName, IXMLCStr attributeValue=NULL, int *i=NULL) const
return child node with specific name/attribute (return an empty node if failing)
ITCXMLNode getChildNodeByPath (IXMLCStr path, IXMLChar sep='/') const
return the first child node with specific path
ITCXMLNode getChildNodeByPathNonConst (IXMLStr path, IXMLChar sep='/') const
return the first child node with specific path
IXMLCStr getElementByPath (IXMLCStr xpath, IXMLChar sep='/') const
return the text content of the given simplified XPATH
IXMLCStr getElementByPathNonConst (IXMLStr xpath, IXMLChar sep='/') const
return the text content of the given simplified XPATH
int nChildNode (IXMLCStr name) const
return the number of child node with specific name
int nChildNode () const
nbr of child node
IXMLAttribute getAttribute (int i=0) const
return ith attribute
IXMLCStr getAttributeName (int i=0) const
return ith attribute name
IXMLCStr getAttributeValue (int i=0) const
return ith attribute value
char isAttributeSet (IXMLCStr name) const
test if an attribute with a specific name is given
IXMLCStr getAttribute (IXMLCStr name, int i) const
return ith attribute content with specific name (return a NULL if failing)
IXMLCStr getAttribute (IXMLCStr name, int *i=NULL) const
return next attribute content with specific name (return a NULL if failing)
int nAttribute () const
nbr of attribute
IXMLClear getClear (int i=0) const
return ith clear field (comments)
int nClear () const
nbr of clear field
int nElement () const
nbr of different contents for current node
char isEmpty () const
is this node Empty?
char isProcessInstruction () const
is this node a Process instruction <? .... ?>
IXMLNode deepCopy () const
deep copy (duplicate/clone) a IXMLNode
ICXMLNode deepCopyConstant () const
deep copy (duplicate/clone) a IXMLNode
ITCXMLNode (const ITCXMLNode &A)
to allow shallow/fast copy:
ITCXMLNode & operator= (const ITCXMLNode &A)
to allow shallow/fast copy:
ITCXMLNode ()
Static Public Member Functions
static ITCXMLNode emptyNode ()
return IXMLNode::emptyIXMLNode;
static IXMLCStr getErrorMessage (IXMLError error)
this gives you a user-friendly explanation of the parsing error
Static Public Attributes
static ITCXMLNode emptyITCXMLNode
static IXMLClear emptyIXMLClear
static IXMLAttribute emptyXMLAttribute
Friends
class IXMLDomParser
class IXMLNode
class ICXMLNode
class IXMLRenderer
Detailed Description
Main Class representing a Incredible Transient Constant XML node.
Most operations are performed using this class.
Note
The constructors of the ITCXMLNode class are protected, so use instead one of these four methods to get your first instance of ITCXMLNode:
IXMLDomParser::parseString
IXMLDomParser::parseFile
IXMLDomParser::openFileHelper
IXMLDomParser::parse
IXMLDomParser::parseOneChild
Definition at line 957 of file IXMLParser.h.
Constructor & Destructor Documentation
ITCXMLNode::ITCXMLNode (const ITCXMLNode & A)
to allow shallow/fast copy:
ITCXMLNode::ITCXMLNode () inline
Definition at line 1005 of file IXMLParser.h.
Member Function Documentation
IXMLNode ITCXMLNode::deepCopy () const
deep copy (duplicate/clone) a IXMLNode
Referenced by example10(), example5(), and example6().
ICXMLNode ITCXMLNode::deepCopyConstant () const
deep copy (duplicate/clone) a IXMLNode
static ITCXMLNode ITCXMLNode::emptyNode () static
return IXMLNode::emptyIXMLNode;
IXMLAttribute ITCXMLNode::getAttribute (int i = 0) const
return ith attribute
Referenced by example1(), and example2().
IXMLCStr ITCXMLNode::getAttribute (IXMLCStr name, int i) const
return ith attribute content with specific name (return a NULL if failing)
IXMLCStr ITCXMLNode::getAttribute (IXMLCStr name, int * i = NULL) const
return next attribute content with specific name (return a NULL if failing)
IXMLCStr ITCXMLNode::getAttributeName (int i = 0) const
return ith attribute name
Referenced by example7().
IXMLCStr ITCXMLNode::getAttributeValue (int i = 0) const
return ith attribute value
Referenced by example1(), and example7().
ITCXMLNode ITCXMLNode::getChildNode (int i = 0) const
return ith child node
Referenced by example1().
ITCXMLNode ITCXMLNode::getChildNode (IXMLCStr name, int i) const
return ith child node with specific name (return an empty node if failing). If i==-1, this returns the last IXMLNode with the given name
ITCXMLNode ITCXMLNode::getChildNode (IXMLCStr name, int * i = NULL) const
return next child node with specific name (return an empty node if failing)
ITCXMLNode ITCXMLNode::getChildNodeByPath (IXMLCStr path, IXMLChar sep = '/') const
return the first child node with specific path
Referenced by example1().
ITCXMLNode ITCXMLNode::getChildNodeByPathNonConst (IXMLStr path, IXMLChar sep = '/') const
return the first child node with specific path
ITCXMLNode ITCXMLNode::getChildNodeWithAttribute (IXMLCStr tagName, IXMLCStr attributeName, IXMLCStr attributeValue = NULL, int * i = NULL) const
return child node with specific name/attribute (return an empty node if failing)
IXMLClear ITCXMLNode::getClear (int i = 0) const
return ith clear field (comments)
Referenced by example1(), and example7().
IXMLCStr ITCXMLNode::getElementByPath (IXMLCStr xpath, IXMLChar sep = '/') const
return the text content of the given simplified XPATH
Referenced by example12().
IXMLCStr ITCXMLNode::getElementByPathNonConst (IXMLStr xpath, IXMLChar sep = '/') const
return the text content of the given simplified XPATH
static IXMLCStr ITCXMLNode::getErrorMessage (IXMLError error) static
this gives you a user-friendly explanation of the parsing error
IXMLCStr ITCXMLNode::getName () const
name of the node
Referenced by example10(), and example7().
ITCXMLNode ITCXMLNode::getParentNode () const
return the parent node
IXMLCStr ITCXMLNode::getText (int i = 0) const
return ith text field
Referenced by example1().
char ITCXMLNode::isAttributeSet (IXMLCStr name) const
test if an attribute with a specific name is given
char ITCXMLNode::isEmpty () const
is this node Empty?
char ITCXMLNode::isProcessInstruction () const
is this node a Process instruction <? .... ?>
int ITCXMLNode::nAttribute () const
nbr of attribute
int ITCXMLNode::nChildNode (IXMLCStr name) const
return the number of child node with specific name
Referenced by example1().
int ITCXMLNode::nChildNode () const
nbr of child node
int ITCXMLNode::nClear () const
nbr of clear field
int ITCXMLNode::nElement () const
nbr of different contents for current node
Referenced by example7().
int ITCXMLNode::nText () const
nbr of text field
ITCXMLNode& ITCXMLNode::operator= (const ITCXMLNode & A)
to allow shallow/fast copy:
Friends And Related Function Documentation
friend class ICXMLNode friend
Definition at line 961 of file IXMLParser.h.
friend class IXMLDomParser friend
Definition at line 959 of file IXMLParser.h.
friend class IXMLNode friend
Definition at line 960 of file IXMLParser.h.
friend class IXMLRenderer friend
Definition at line 962 of file IXMLParser.h.
Member Data Documentation
ITCXMLNode ITCXMLNode::emptyITCXMLNode static
Definition at line 1005 of file IXMLParser.h.
IXMLClear ITCXMLNode::emptyIXMLClear static
Definition at line 1007 of file IXMLParser.h.
IXMLAttribute ITCXMLNode::emptyXMLAttribute static
Definition at line 1008 of file IXMLParser.h.
The documentation for this class was generated from the following file:
IXMLParser.h