IncredibleXMLParser: Deleting Nodes or Attributes
Deleting Nodes or Attributes
Edit/Update the IXMLNode structure
Functions
void IXMLNode::deleteNodeContent ()
The "deleteNodeContent" function forces the deletion of the content of this IXMLNode and the subtree.
void IXMLNode::deleteAttribute (int i=0)
Delete the ith attribute of the current IXMLNode.
void IXMLNode::deleteAttribute (IXMLCStr pName)
Delete the attribute with the given name (the "strcmp" function is used to find the right attribute)
void IXMLNode::deleteAttribute (IXMLAttribute *anAttribute)
Delete the attribute with the name "anAttribute->pName" (the "strcmp" function is used to find the right attribute)
void IXMLNode::deleteText (int i=0)
Delete the Ith text content of the current IXMLNode.
void IXMLNode::deleteText (IXMLCStr pValue)
Delete the text content "pValue" inside the current IXMLNode (direct "pointer-to-pointer" comparison is used to find the right text)
void IXMLNode::deleteClear (int i=0)
Delete the Ith clear tag inside the current IXMLNode.
void IXMLNode::deleteClear (IXMLCStr pValue)
Delete the clear tag "pValue" inside the current IXMLNode (direct "pointer-to-pointer" comparison is used to find the clear tag)
void IXMLNode::deleteClear (IXMLClear *p)
Delete the clear tag "p" inside the current IXMLNode (direct "pointer-to-pointer" comparison on the pName of the clear tag is used to find the clear tag)
Detailed Description
See the functions example3() and example5() for some usage examples.
Function Documentation
void IXMLNode::deleteAttribute (int i = 0)
Delete the ith attribute of the current IXMLNode.
Referenced by example3().
void IXMLNode::deleteAttribute (IXMLCStr pName)
Delete the attribute with the given name (the "strcmp" function is used to find the right attribute)
void IXMLNode::deleteAttribute (IXMLAttribute * anAttribute)
Delete the attribute with the name "anAttribute->pName" (the "strcmp" function is used to find the right attribute)
void IXMLNode::deleteClear (int i = 0)
Delete the Ith clear tag inside the current IXMLNode.
void IXMLNode::deleteClear (IXMLCStr pValue)
Delete the clear tag "pValue" inside the current IXMLNode (direct "pointer-to-pointer" comparison is used to find the clear tag)
void IXMLNode::deleteClear (IXMLClear * p)
Delete the clear tag "p" inside the current IXMLNode (direct "pointer-to-pointer" comparison on the pName of the clear tag is used to find the clear tag)
void IXMLNode::deleteNodeContent ()
The "deleteNodeContent" function forces the deletion of the content of this IXMLNode and the subtree.
Note
The IXMLNode instances that are referring to the part of the subtree that has been deleted CANNOT be used anymore!!. Unexpected results will occur if you continue using them.
Referenced by example3(), and example5().
void IXMLNode::deleteText (int i = 0)
Delete the Ith text content of the current IXMLNode.
Referenced by example3().
void IXMLNode::deleteText (IXMLCStr pValue)
Delete the text content "pValue" inside the current IXMLNode (direct "pointer-to-pointer" comparison is used to find the right text)