IncredibleXMLParser: Save the content of an IXMLNode inside a file.
Save the content of an IXMLNode inside a file.
Creating XML files or XML Strings.
Functions
IXMLError IXMLRenderer::writeToFile (ITCXMLNode x, IXMLCStr filename, IXMLCStr encoding=NULL, char nFormat=1)
Save the content of an ITCXMLNode inside a file.
IXMLError IXMLRenderer::writeToFile (ICXMLNode x, IXMLCStr filename, IXMLCStr encoding=NULL, char nFormat=1)
Save the content of an ITCXMLNode inside a file.
IXMLError IXMLRenderer::writeToFile (IXMLNode x, IXMLCStr filename, IXMLCStr encoding=NULL, char nFormat=1)
Save the content of an ITCXMLNode inside a file.
Detailed Description
If nFormat==0, no formatting is required otherwise this returns an user friendly XML string from a given element with appropriate white spaces and carriage returns. If the global parameter "characterEncoding==encoding_UTF8", then the "encoding" parameter is ignored and always set to "utf-8". If the global parameter "characterEncoding==encoding_ShiftJIS", then the "encoding" parameter is ignored and always set to "SHIFT-JIS". If "_XMLWIDECHAR=1", then the "encoding" parameter is ignored and always set to "utf-16". If no "encoding" parameter is given the "ISO-8859-1" encoding is used.
See the functions example1() and example9() for some usage examples.
Function Documentation
IXMLError IXMLRenderer::writeToFile (ITCXMLNode x, IXMLCStr filename, IXMLCStr encoding = NULL, char nFormat = 1)
Save the content of an ITCXMLNode inside a file.
Referenced by example1(), example12(), and example9().
IXMLError IXMLRenderer::writeToFile (ICXMLNode x, IXMLCStr filename, IXMLCStr encoding = NULL, char nFormat = 1)
Save the content of an ITCXMLNode inside a file.
IXMLError IXMLRenderer::writeToFile (IXMLNode x, IXMLCStr filename, IXMLCStr encoding = NULL, char nFormat = 1)
Save the content of an ITCXMLNode inside a file.