IncredibleXMLParser: Creating from scratch a IXMLNode structure
Creating from scratch a IXMLNode structure
Edit/Update the IXMLNode structure
Functions
static IXMLNode IXMLNode::createXMLTopNode (IXMLCStr pName=NULL, char isDeclaration=FALSE)
Create the top node of an IXMLNode structure.
IXMLNode IXMLNode::addChild (IXMLCStr pName, char isDeclaration=FALSE, IXMLElementPosition pos=-1)
Add a new child node.
IXMLNode IXMLNode::addChild (IXMLNode nodeToAdd, IXMLElementPosition pos=-1)
If the "nodeToAdd" has some parents, it will be detached from it's parents before being attached to the current IXMLNode.
IXMLAttribute * IXMLNode::addAttribute (IXMLCStr pName, IXMLCStr pValuev)
Add a new attribute.
IXMLCStr IXMLNode::addText (IXMLCStr pValue, IXMLElementPosition pos=-1)
Add a new text content.
IXMLClear * IXMLNode::addClear (IXMLCStr pValue, IXMLCStr lpcOpen=NULL, IXMLCStr lpcClose=NULL, IXMLElementPosition pos=-1)
Detailed Description
See the function example3() for some usage examples.
Function Documentation
IXMLAttribute* IXMLNode::addAttribute (IXMLCStr pName, IXMLCStr pValuev)
Add a new attribute.
Referenced by example3().
IXMLNode IXMLNode::addChild (IXMLCStr pName, char isDeclaration = FALSE, IXMLElementPosition pos = -1)
Add a new child node.
Referenced by example3(), and example6().
IXMLNode IXMLNode::addChild (IXMLNode nodeToAdd, IXMLElementPosition pos = -1)
If the "nodeToAdd" has some parents, it will be detached from it's parents before being attached to the current IXMLNode.
IXMLClear* IXMLNode::addClear (IXMLCStr pValue, IXMLCStr lpcOpen = NULL, IXMLCStr lpcClose = NULL, IXMLElementPosition pos = -1)
Add a new clear tag
Parameters
lpcOpen default value "<![CDATA["
lpcClose default value "]]>"
IXMLCStr IXMLNode::addText (IXMLCStr pValue, IXMLElementPosition pos = -1)
Add a new text content.
Referenced by example3().
static IXMLNode IXMLNode::createXMLTopNode (IXMLCStr pName = NULL, char isDeclaration = FALSE) static
Create the top node of an IXMLNode structure.
Referenced by example3().